from __future__ import annotations

from pathlib import Path

# (doc_type, keywords) — higher-weight keywords should be specific phrases
TYPE_KEYWORDS: list[tuple[str, list[str]]] = [
    ("invoice",         ["invoice", "bill to", "invoice no", "invoice #", "invoice number",
                         "amount due", "due date", "remit to", "payment terms", "tax invoice",
                         "vat invoice", "subtotal", "net 30", "net 60"]),
    ("receipt",         ["receipt", "thank you for your purchase", "total paid",
                         "payment received", "cash receipt", "transaction id",
                         "receipt number", "amount paid", "change due"]),
    ("purchase_order",  ["purchase order", "po number", "po #", "po no",
                         "ship to", "vendor", "order date", "ordered by",
                         "unit price", "qty", "line total"]),
    ("contract",        ["contract", "agreement", "parties agree", "whereas",
                         "hereinafter", "terms and conditions", "in witness whereof",
                         "obligations", "termination", "indemnification",
                         "governing law", "effective date", "executed by"]),
    ("nda",             ["non-disclosure", "nda", "confidentiality agreement",
                         "confidential information", "disclosing party",
                         "receiving party", "proprietary information",
                         "trade secret", "shall not disclose"]),
    ("statement",       ["account statement", "statement of account",
                         "opening balance", "closing balance", "transactions",
                         "debit", "credit", "balance forward"]),
    ("bank_statement",  ["bank statement", "account number", "sort code",
                         "iban", "swift", "bic", "branch", "available balance",
                         "account holder", "overdraft"]),
    ("tax_document",    ["tax return", "w-2", "w2", "1099", "irs", "taxable income",
                         "gross income", "federal tax", "state tax", "tax year",
                         "social security number", "employer identification",
                         "adjusted gross income", "filing status"]),
    ("payslip",         ["payslip", "pay stub", "pay slip", "earnings statement",
                         "gross pay", "net pay", "deductions", "employer", "employee",
                         "pay period", "hours worked", "ytd", "year to date",
                         "pension", "national insurance", "withholding"]),
    ("insurance",       ["insurance", "policy number", "premium", "coverage",
                         "deductible", "insured", "policyholder", "claim",
                         "beneficiary", "underwriter", "effective coverage",
                         "expiry date", "insurance certificate"]),
    ("medical_record",  ["patient", "diagnosis", "prescription", "medication",
                         "physician", "doctor", "clinic", "hospital", "symptoms",
                         "treatment", "dosage", "date of birth", "medical history",
                         "referral", "icd", "cpt"]),
    ("quote",           ["quotation", "quote #", "estimate", "validity",
                         "valid until", "quote date", "quoted by", "proposal",
                         "unit cost", "discount", "total estimate",
                         "labour cost", "parts cost"]),
    ("delivery_note",   ["delivery note", "packing list", "packing slip",
                         "consignment", "tracking number", "shipped to",
                         "carrier", "delivery date", "goods received",
                         "despatch", "dispatch note"]),
    ("form",            ["please complete", "fill in", "applicant",
                         "application form", "questionnaire",
                         "check all that apply", "signature", "date of birth",
                         "please print clearly"]),
    ("report",          ["executive summary", "prepared by", "findings",
                         "conclusion", "recommendations", "methodology",
                         "table of contents", "appendix", "data analysis"]),
    ("resume",          ["curriculum vitae", " cv ", "work experience",
                         "employment history", "education", "references available",
                         "skills", "objective", "professional summary",
                         "certifications", "linkedin"]),
    ("letter",          ["dear ", "sincerely,", "yours truly",
                         "to whom it may concern", "kind regards", "best regards",
                         "re:", "subject:", "yours faithfully"]),
    ("specification",   ["specification", "requirements document",
                         "revision history", "scope of work", "deliverables",
                         "functional requirements", "non-functional",
                         "acceptance criteria", "user story"]),
]

ROUTE_TO_TYPE: dict[str, str] = {
    "image":        "image",
    "spreadsheet":  "spreadsheet",
    "presentation": "presentation",
    "email":        "email",
    "html":         "webpage",
    "json":         "data",
    "xml":          "data",
    "archive":      "archive",
}
